g++ fetchip.cpp -o fetchip
./fetchip
./fetchop.sh
./fetchop.sh 1
g++ cleanop.cpp -o cleanop
./cleanop 1
./fetchip 2 mh
./fetchop.sh 2
./cleanop 2
./fetchip 3 mhmh
./fetchop.sh 3
./cleanop 3
./fetchip 4 mhmhmg
./fetchop.sh 4
./cleanop 4
./fetchip 5 mhmhmglu
./fetchop.sh 5
./cleanop 5
./fetchip 6 mhmhmglulh
./fetchop.sh 
./cleanop 6
./fetchip 7 mhmhmglulhmm
./fetchop.sh 7
./cleanop 7
./fetchip 7 mhmhmglulhmmmi
./fetchip 8 mhmhmglulhmmmi
./fetchop.sh 8
./cleanop 8
./fetchip 1 li
./fetchip 2 li
./fetchop.sh 2
./cleanop 2
./fetchip 3 ligj
./fetchop.sh 3
./cleanop 3
./fetchip 3 liln
./fetchop.sh 3
./cleanop 3
./fetchip 4 lilnif
./fetchop.sh 4
./cleanop 4
./fetchip 5 lilnifif
./fetchop.sh 5
./cleanop 5
./fetchip 6 lilnififif
./fetchop.sh 6
./cleanop 6
./fetchip 7 lilnifififif
./fetchop.sh 7
./cleanop 7
./fetchip 8 lilnififififif
./fetchop.sh 8
./cleanop 8
g++ asciicode.cpp -o asciicode
./asciicode mhmhmglulhmmmilulilnifififififif
